[package]
name = "text"
version = "0.1.0"
edition = "2024"

[dependencies]
framework = { version = "0.1.0", path = "../framework" }
anyhow.workspace = true
wgpu.workspace = true
ab_glyph.workspace = true
glam.workspace = true
bytemuck.workspace = true
web-time.workspace = true
serde.workspace = true
serde_json.workspace = true
fontdue = "0.9.3"
